version: '3'
services:
  iot_gateway:
    build: ./iot_gateway
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./logs:/logs
  sensor:
    build: ./sensor
    environment:
      - TZ=Europe/Berlin
  cloud_server:
    build: ./cloud_server
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./logs:/logs
  database:
    build: ./database
    environment:
      - TZ=Europe/Berlin
  mqtt_adapter:
    build: ./mqtt_adapter
    environment:
      - TZ=Europe/Berlin
  mqtt_sensor:
    build: ./mqtt_sensor
    environment:
      - TZ=Europe/Berlin
  mosquitto_broker:
    build: ./mqtt_broker
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config/conf.d:rw
      - ./log:/mosquitto/log:rw
    environment:
      - TZ=Europe/Berlin
