version: '3'
services:
  iot_gateway:
    build: ./iot_gateway
    container_name: iot_gateway
    environment:
      - TZ=Europe/Berlin
  sensor:
    build: ./sensor
    environment:
      - TZ=Europe/Berlin



