version: '3'
services:
  iot_gateway:
    build: ./iot_gateway
    container_name: iot_gateway
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /Users/alexbreiter/Dateien/Studium_h-da/Semester4/VerteilteSysteme/Praktikum/Di2x-A/logs:/logs
  sensor:
    build: ./sensor
    environment:
      - TZ=Europe/Berlin



