version: '3'
services:
  iot_gateway:
    build: ./iot_gateway
    container_name: iot_gateway
  sensor:
    build: ./sensor
    container_name: sensor
    environment:
      - ID=1
  sensor2:
    build: ./sensor
    container_name: sensor2
    environment:
      - ID=2


